language: cpp
compiler:
- clang
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - pkg-config
script: "mkdir build && cd build && cmake .. && make check"
